### ISSUE TITLE
Add java.util.UUID support for JSON

### ISSUE THREAD

**Issue by paulroemer** [eclipse/vert.x#1321]
Hi,

I'm using the JDBC client to query my database. Unfortunately, I'm also using java.util.UUIDs which the vert.x JSON abstraction does not support. Converting it to a String does not work because the DB expect a UUID.

Is it possible/allowed to extend the supported datatypes? I've read that jackson supports UUIDs out-of-the-box. I hope that this will fix my problem.

Cheers,
  Paul

**Comment by paulroemer** [comment]
I extended the Json.checkAndCopy method to allow UUIDs. Moreover I updated some of the unit tests. Unfortunately, the UUID datatype is ignored by Vert.x codegen which prevents me from writing DataObjectTests and code generation for other languages will fail. 

Am I right? Any suggestions? In the end an UUID is a simple string that should be supported by any supported language...

Cheers,
  Paul

**Comment by pmlopes** [comment]
UUID is not a valid JSON type, see: http://json.org/

What you can do is add _write_ only support for it, the same way we have for temporal types, but but only if there is a RFC describing the encoding otherwise you're building a non standard feature.

For JDBC there is now a PR that you should look at since it implements optimistic casting for a couple of types, currently, TIME, DATE, TIMESTAMP, UUID, maybe we could even consider to extend it for ARRAY and BINARY in the future.

**Comment by paulroemer** [comment]
Thanks Paulo for the clarification. Currently I'm working with a patched Vert.x and will wait for the upcoming release.

**Comment by JV-TM** [comment]
We would very appreciate UUID support. UUID serialization is straight forward (ISO format toString / fromString). So, it should be relativelly easy. 

io.vertx.core.json.Json#checkAndCopy()
else if (val instanceof UUID) {
  val = val.toString();
}

io.vertx.codegen.ClassModel#checkParamType()
...

**Comment by blandger** [comment]
Hi vertx folks,
I would like to pop up that issue with question related to java code generation. 
How can I use UUID as part of ServiceProxy generation? Gradle 4.3.1 is used.

I'm trying to use example from here:
https://github.com/advantageous/vertx-node-ec2-eventbus-example/wiki/Step-5-Using-Vertx-Service-Proxies

e.g. I have DTO as:
@DataObject
public class MyEntityDTO {
  private UUID myEntityId;
....
  public MyEntityDTO(JsonObject data) {....}
}

Service Proxy Interface like:
@ProxyGen
@VertxGen
public interface MyEntityServiceAsynch {
void save(MyEntityDTO entity, Handler<AsyncResult<UUID>> resultHandler);
....}

I have 'package-info.java' files in folders, but don't understand how can I generate UUIDs.

Could not generate model for .....service.MyEntityServiceAsynch#save(.....dto.MyEntityDTO,io.vertx.core.Handler<io.vertx.core.AsyncResult<java.util.UUID>>): type io.vertx.core.Handler<io.vertx.core.AsyncResult<java.util.UUID>> is not legal for use for a parameter in code generation
  void save(MyEntityDTO entity, final Handler<AsyncResult<UUID>> resultHandler);
       ^
warning: The following options were not recognized by any processor: '[outputDirectory]'


I'm appreciate for any hint.

**Comment by arr-ee** [comment]
@pmlopes that’s interesting since https://github.com/vert-x3/vertx-jdbc-client/pull/49 exists. Right now, it’s possible to _read_ uuids from pg, but not write them _if_ pg column has a type of `json`.

https://tools.ietf.org/html/rfc4122#page-29, along with https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html#toString-- and http://www.ossp.org/pkg/lib/uuid/ list textual representation of UUID as an equivalent of `[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}` — maybe it’d be worth it to support this conversion in vertx as well?

I can provide a pull request in case you reconsider your stance on this.

Thanks!

**Comment by pmlopes** [comment]
@arr-ee I think it should be OK to have helpers to convert from non-json types to standard serialization, as we do have for `Instant` and `byte[]` so I guess adding such an encoder for `UUID` could be acceptable **but** the internal representation has to be a `String` since once we need to encode the object to send over the wire (either the eventbus or other format) we would break the `JSON` format.

`UUID` is a well known format so it can safely be added i think.

On the other hand to make this more robust we should investigate on how to add support for these types at `codegen` level so all languages could benefit and we could delay the encode/decode only to the time the data needs to go over the wire.
