### ISSUE TITLE
DNS search domains resolution

### ISSUE THREAD

**Issue by vietj** [eclipse/vert.x#1475]
Implements DNS search domains for the AddressResolver

**Comment by luengnat** [comment]
@vietj 

Let's say I have my DNS configuration to have a search path
acme.com

but when I try to connect to a server www.acme.com, it seems to try to resolve www.acme.com.acme.com even though www.acme.com exists. I wonder whether the current code is to perform DNS resolution in parallel or not. Occasionally, I seem to get DNS resolution error from time to time because of this.

**Comment by vietj** [comment]
@luengnat have you tried with Vert.x `3.4.0-SNAPSHOT` ?

**Comment by luengnat** [comment]
@vietj do you know what could be the problem in vert.x 3.3.3 that might cause the problem? I can't seem to reproduce it with public dns. The issue seems to only happen with private DNS so far so it is a bit difficult for me to reproduce the exact issue.

**Comment by vietj** [comment]
@luengnat it can be an server response sent by your private DNS that Netty's decoder does not understand correctly like this issue https://github.com/netty/netty/issues/5391 .

Can you capture the DNS UDP traffic with wireshark when it happens ?
