### ISSUE TITLE
DeliveryOptions should have a toJson() method

### ISSUE THREAD

**Issue by aschrijver** [eclipse/vert.x#1502]
While the `toJson()` method on a data object is optional IMHO the 'vertx-provided' data objects should be feature-complete by default and contain this method.

Also when referring to the service-proxies documentation (section on Proxy creation):

> Generally, service interface contains a createProxy static method to create the proxy. But this is not required

But then this code leads to an error in code generation:

``` java
static MyService createProxy(Vertx vertx, String address, DeliveryOptions options) {
    return ProxyHelper.createProxy(MyService.class, vertx, address, options);
}
```

Error:

```
error: Could not generate model for createProxy(io.vertx.core.Vertx,java.lang.String,io.vertx.core.eventbus.DeliveryOptions): type io.vertx.core.eventbus.DeliveryOptions does not have a valid 'public JsonObject toJson()' method.
    static MyService createProxy(Vertx vertx, String address, DeliveryOptions options) {
                     ^
```

If agreeing with this change, I'll create a PR.

**Comment by pmlopes** [comment]
Would it be an idea to add a `Options` interface that all options objects would implement which would provide a `toJSON()` `fromJSON(JsonObject obj)`? this would help us identify option classes and ensure that we can always convert to/from `JSON`.

**Comment by aschrijver** [comment]
That would be nice, yes. It leaves the option to add / omit the `@DataObject` annotation.

**Comment by vietj** [comment]
a couple of comments:

An Options like interface is not needed, the only benefit would be to allow a library to convert anything to a `JsonObject` with a `toJson` method that exists. Without that, a library cannot convert a data object to a `JsonObject` because it would need to use Java reflection to invoke the method.

Technically, only the `JsonObject` constructor is necessary for a data object, the `toJson ` is not necessary. Adding this would force the data object implementor to add some code he may not want to add. That being said the current `JsonObjectConverter` helps much because it generates this boiler-plate code for the user, and this adds the ability to use data object more freely in service proxies. At the same time, the service proxy code could use the generated `JsonObjectConverter` to convert the data object to json when the `toJson` method does not exist.

Finally, such options would rather denote that is convertible from/to `JsonObject` and it is not necessarily tied to the data object, i.e a data object could implement such interface but it could be used in other places, so it's a more general discussion than this one that is about adding `toJson` to the `DeliveryOptions` (which makes sense to me).

**Comment by tsegismont** [comment]
I went ahead and added a `toJson` method in #2072 

Such methods have been added to other option classes recently. Let's continue adding them case by case.
