### ISSUE TITLE
Expose io.vertx.core.http.impl.MimeMapping methods to public API

### ISSUE THREAD

**Issue by cstamas** [eclipse/vert.x#1608]
Vert.x http uses this class to figure mime, but this class is not accessible via public API. Would be nice to have the methods `getMimeTypeForExtension` and `getMimeTypeForFilename` accessible via public API too.

**Comment by jaguililla** [comment]
I'm able to use `MimeMapping` from client code. Should this task be closed? @cstamas

**Comment by vietj** [comment]
you mean implemented ?

**Comment by jaguililla** [comment]
I meant that `MimeMapping` class (including getMimeTypeForExtension and getMimeTypeForFilename) is not Vert.x internal (I was able to use it from outside of Vertx code). Because I though that the proposal is to include them in the public methods of Vertx.

I just arrived here thinking the same, and now I realize I can use that functionality.

So I though the issue could be closed because it can be confusing for other people.
