### ISSUE TITLE
vertx (non clustered) don't instant sends messages while processing handlers!

### ISSUE THREAD

**Issue by tetv** [eclipse/vert.x#1631]
It seems that `vertx` in some cases doesn't send messages instantaneously.
That means while a `vertx` is very busy/active there is no messages dispatched to eventBus until the `vertx` becomes completely idle, that could be a big limitation if there is a need to send messages immediately.

For **non clustered** vertx, the issue happens when using `vertx.executeBlocking` (non ordered) or when processing default code in a `Multi-Thread Worker`.

To illustrate the issues, I created a simple ping pong example with **junit tests**.
- Ping sends several messages to pong;
- Pong emulates a 50ms processing time and reply back the message to ping.
- Ping, in some cases, doesn't receive immediately the message after pong has processed it.

The tests includes two workarounds (while the fix is not available)  that solves the issue:
- using `WorkerExecutor` (available since vertx 3.3.x) - [Vertx documentation](http://vertx.io/docs/vertx-core/java/#blocking_code)
- using java `ExecutorService`

Test source code is available here: https://github.com/tetv/vertx3-blocking (using vertx 3.3.3)

| v Test Type / Pong Verticle Type > | Standard | Worker | MT Worker |
| --- | --- | --- | --- |
| Direct code (No executeBlocking) | :heavy_check_mark: | :heavy_check_mark: | :heavy_multiplication_x:`≥ 40` |
| vertx.executeBlocking(ordered) | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| vertx.executeBlocking(not ordered) | :heavy_multiplication_x:`≥ 40` | :heavy_multiplication_x:`≥ 40` | :heavy_multiplication_x:`≥ 40` |
| workerExecutor.executeBloking(ordered) | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| workerExecutor.executeBloking(not ordered) | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| javaExecutor.process(ordered) | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| javaExecutor.process(not ordered) | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

**Note:** There is also an identical issue but for clustered vertx: https://github.com/vert-x3/vertx-hazelcast/issues/43

**Comment by tsegismont** [comment]
I had a look at the tests today, this scenario in particular:

```
{ LOCAL,   WORKER,    "block",   NOT_ORDERED, 20, 39, 40 }
```

The `send_3rd_messages` method fails indeed, but it's not because Vert.x doesn't instantly send messages. It fails because sometimes Vert.x sent more than the test expected. Sometimes less. Or sometimes (rarely) the expected number of replies is received, but not in the expected order. I'm not surprised, if you use vertx.executeBlocking with order = false, then there are some chances that a task submitted first gets executed after, because the scheduler could give priority to one thread over the other.

There are different issues with the test implementation but here are two major ones:

- you can't reliably measure durations using System.currentTimeMillis calls; the granularity of the result depends on the system and is important (often around 10ms)
- when the test checks the replies, it doesn't take a snapshot of the collection, it takes a reference to the instance in the Ping verticle; so by the time the collection size and content are evaluated, more messages could have been added.

For those reasons, I believe the test is invalid and the issue should be closed.

**Comment by tetv** [comment]
Hi @tsegismont, at that time, I did lots of tests and the conclusion was that it really blocks.

The `vertx` processing times are almost instantaneous. However you can change the `PONG_WAIT` to 1000 (1 second) in order to confirm what I am telling you. You can play as well with the variables `SEND_TIME` and `CHECK_TIME`.

My understanding is that the message is only send if there is working threads available.
  `Case 1 - 20 messages`: Initially all 20 working threads are processing and blocked, but after one working thread finishes, it start sending.
  `Case 2 - 39 messages`: Initially all 20 working threads are processing and blocked, then 19 working threads start processing the next batch of 19 and therefore are blocked but there is one thread empty that start sending the first 20 processed answers (it's the last worker thread that have finished the first batch of 20).
  `Case 3 - 40 messages`: Initially all 20 working threads are processing and blocked, then again all 20 working threads start processing the next batch of 20 and because of that, all of then are still blocked, and none of the initially 20 answers are sent until a working threads is available.

**Comment by tetv** [comment]
Updated the junit project to use **vertx 3.4.0**, and also have simplified it and improve logging.

**Comment by tsegismont** [comment]
Closing: I had a look at the updated project. It's still difficult for me to understand what the script does and what are the expectations vs the reality.

**Comment by tetv** [comment]
Hi @tsegismont, it's much easier to close, than to try to emulate the issue by yourself. :(
What do you want from me in order to proof that there is this two issues?
- **vertx.executeBlocking(not ordered)** and **direct code in MT**?
