### ISSUE TITLE
Upgrade to Netty 4.1.6.Final

### ISSUE THREAD

**Issue by vietj** [eclipse/vert.x#1681]

**Comment by dconnelly** [comment]
Is this slated for the next Vertx release? Grpc 1.0.2 just upgraded to 4.1.6.Final and otherwise it's impossible to mix the two together.

**Comment by vietj** [comment]
yes, at least this version.

have you been using Vert.x and GRPC together so far ?

**Comment by normanmaurer** [comment]
@vietj just a heads we will release netty 4.1.7.Final next week.

**Comment by vietj** [comment]
@normanmaurer thanks just updated this issue

**Comment by dconnelly** [comment]
@vietj Yes we've been happily using vertx http server for our front-end api server combined with grpc for our backend micro-services, which works well as long as the netty versions are compatible. Before jumping to 4.1.7.Final would it be be worth checking to make sure that grpc 1.0.2 is compatible?

**Comment by vietj** [comment]
@dconnelly indeed, but at some point it will migrate I guess

**Comment by vietj** [comment]
@dconnelly do you have specific integration with Vert.x ? like event loop integration

**Comment by dconnelly** [comment]
We've just started using vert.x for our front-end api server, with our own protobuf-based rpc over http/2. I started with vert.x embedded but quickly found it easier to just deploy a verticle, otherwise the context management quickly gets hairy. The front-end server also uses grpc to talk to our backend microservices for account management etc and it would be super nice if there were an option to run grpc over vert.x. We plan on slowly moving other internal clients such as redis, jdbc over to vert.x as well.

**Comment by vietj** [comment]
created this https://github.com/eclipse/vert.x/issues/1734

**Comment by vietj** [comment]
@dconnelly I groked this integration of Vert.x and gRPC, perhaps you want to give a try and provide feedback ? https://github.com/vietj/vertx-grpc

**Comment by dconnelly** [comment]
@vietj Very good start I will check it out and give feedback.

**Comment by vietj** [comment]
@dconnelly there is no doc per se, but the tests are pretty much self explanatory
