### ISSUE TITLE
how many max connections vertx eventbus can have ?

### ISSUE THREAD

**Issue by sandipsahoo2k2** [eclipse/vert.x#1885]
I have done multiple projects with vertx so far and quite happy with its performance. Would like to know if it would be suitable for writing a GPS tracking server. My plan is to handle around 100,000 simultaneous connection initially. Can I use eventbus for such loads and would it be possible for vertx server to handle.

**Comment by vietj** [comment]
what do you call connection in the context of event bus ?

**Comment by tsegismont** [comment]
I guess you GPS enabled devices would connect over an event bus bridge,
right?

Then I believe it's possible. You may have to use a TCP load balancer so
that event bus bridge connections from devices to Vert.x servers do not go
to the same server.

2017-03-22 5:02 GMT+01:00 Sandeep Sahoo <notifications@github.com>:

**Comment by sandipsahoo2k2** [comment]
Yes I am targeting GPS Enabled Devices as the client and I mean a connection mean one unique Client. 
Yes All these devices would connect to EventBus Bridge. 
So you mean to say that I have to run multiple parallel vertx servers with a TCP Load balancers.
I have already thought of it anyway I wanted to know how many connections can be handled by one vertx server .. I just want to have an idea about it so that I can design accordingly.

**Comment by tsegismont** [comment]
There's no absolute answer to your last question. It depends on the server
hardware, the type of processing your verticles will do, your system
configuration, ... etc.
I can only recommend to do some perf testing in a production like
environment to determine your needs.
You would certainly have at least two servers for high availability.

If you have further questions please continue the thread on the user group
(see the website community page) so that the wider Vert.x community can
chime in.

2017-03-22 11:25 GMT+01:00 Sandeep Sahoo <notifications@github.com>:

**Comment by vietj** [comment]
closing the issue
