### ISSUE TITLE
FileSystem readDir does not list all entries when resolving from Classpath

### ISSUE THREAD

**Issue by oli-h** [eclipse/vert.x#2126]
```
final FileSystem fs = vertx.fileSystem();
fs.propsBlocking("test/one,txt");
fs.readDirBlocking("test/");    // Bump: Only lists "one.txt" - even if there are more files on test/
```
Problem is: FileResolver copies-out resources from Classpath to a temporary directory in filesystem (i.e. .vertx/file-cache-[uuid]/... seen as a _cache_).
If you **first access a single file**, then only this one file is copied-out. A dir-listing hereafter then only lists this single file. Vertx seems to rely on the cache content here.

If you do list the directory contents _before_ accessing a single file, i.e:
```
final FileSystem fs = vertx.fileSystem();
fs.readDirBlocking("test/");    // Yeah - this now lists all files in test/
```
then you see the the whole subtree copied-out of the classpath.

**Comment by Sammers21** [comment]
@oli-h, would mind creating a reproducer(GitHub repo or something else)? 

Also, it would be great to have commentaries with expected and actual behavior.

Thanks,
Pavel

**Comment by fzakaria** [comment]
I'll take a peek.

**Comment by fzakaria** [comment]
What is the expected behavior here?
`FileResolver` adds functionality to resolve files from the classpath (`ENABLE_CP_RESOLVING`) as if they were on disk using the `File` java API -- it does so using the _cache_.

The best solution I can see is _recursively_ copying all files in the parent directory during cache hydration. Thoughts?

**Comment by vietj** [comment]
no thoughts, I 've only created a reproducer
