### ISSUE TITLE
Options generated converter should be package private

### ISSUE THREAD

**Issue by vietj** [eclipse/vert.x#2144]
There is no value to have the currently generated converter to be public classes as they are meant to be used by data objects.

**Comment by MeYoGui** [comment]
Hi ! 

We were using the VertxOptionsConverter class to enable auto configuration of our VertX instances on the fly using our configuration files (in JSON via VertxOptionsConverter.fromJson()).

This class was very helpful for us as we didn't need to map every single configuration key to the VertxOptions manually (avoiding typos, etc.).

Do you think it would be possible to keep that VertxOptionsConverter public instead of "package" ?

Thanks.

**Comment by tsegismont** [comment]
@MeYoGui how about using the constructor taking a json object arg? https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/VertxOptions.java#L207

**Comment by MeYoGui** [comment]
It will do the trick :)
Thank you!

**Comment by tsegismont** [comment]
@MeYoGui starting with 3.6, you no longer need to create your own `Launcher` to tweak the Vert.x options: https://vertx.io/blog/eclipse-vert-x-3-6-0-released/#externalized-configuration-of-vert-x-options

But tbh I'm  not sure about the motivation for hiding converters. cc @vietj ?

**Comment by vietj** [comment]
it's because it's internal and at some point i'm planning to refactor
to generate a single class with many static methods instead of a class per converter.
