### ISSUE TITLE
Why are the CharSequence methods in HttpServerResponse marked @GenIgnore?

### ISSUE THREAD

**Issue by dmolesUC3** [eclipse/vert.x#2211]
This makes it awkward to use the `io.vertx.core.http.HttpHeaders` constants, which are `CharSequences`, with the generated versions (e.g., `io.vertx.reactivex`).

**Comment by vietj** [comment]
because this is not a type understood by the code generator, you can access the underlying `HttpHeader` with `getDelegate()` if you need

**Comment by dmolesUC3** [comment]
Yes, my question is *why* is it not understood by the code generator? What's special about `CharSequence`?

**Comment by EmadAlblueshi** [comment]
Simply because RxJava is considered in code generator like other languages such as Scala, Kotlin ... etc.

**Comment by vietj** [comment]
CharSequence could be perhaps supported by the code generator as String to ease other languages, can you open an issue in codegen for this ?

**Comment by chronodm** [comment]
I don't think I understand the situation well enough to open an issue. Why is `CharSequence` a problem for other JVM languages? It's been part of the Java standard library since version 1.4.

**Comment by vietj** [comment]
codegen defines a specific set of types exposed by the supported languages, String is one of them but not CharSequence. Which methods are you referring to precisely ?

**Comment by chronodm** [comment]
E.g. [HttpServerResponse.putHeader(CharSequence, CharSequence)](http://vertx.io/docs/apidocs/io/vertx/core/http/HttpServerResponse.html#putHeader-java.lang.CharSequence-java.lang.CharSequence-). You can't pass an [HttpHeaders](http://vertx.io/docs/apidocs/io/vertx/core/http/HttpHeaders.html) constant in as the header name, because those constants are all `CharSequence`.

`CharSequence` should be supported by Java, Scala, Groovy, Kotlin, Ceylon, and anything else on the JVM. It seems a shame to limit those, not to mention the various Java APIs, simply because there's no `CharSequence` in JavaScript or Ruby. If anything, it would make more sense to _only_ have the `CharSequence` methods, since a `String` is also a `CharSequence`, and convert them to strings in the non-JVM code generators.

**Comment by chronodm** [comment]
(Note: I'm perfectly willing to believe there's a valid reason for doing things this way, I'm just not seeing it yet.)

**Comment by vietj** [comment]
the reason of these methods is that they are optimized CharSequence implementations that are not String and provide better performances.

CharSequence is supported on these languages, the vertx codegen project that code generate the vertx api for these languages does not support it, so the method with CharSequence type are not exposed in RxJava, JS,Ruby and Scala.

In Groovy and Kotlin, they can be used.

So we can open an issue in the codegen project (https://github.com/vert-x3/vertx-codegen/) to support CharSequence as well.
