### ISSUE TITLE
Clarify that classloading isolation not compatible with Java 9 in documentation

### ISSUE THREAD

**Issue by Marssmart** [eclipse/vert.x#2278]
https://github.com/eclipse/vert.x/blob/5eb55e8478fbe9ca1cb14aaef783a40857fee602/src/main/java/io/vertx/core/impl/DeploymentManager.java#L384

This line cause incompatibility with Java 9 , when combined with attempt to use isolation group.

Java 9
![image](https://user-images.githubusercontent.com/12251937/34984971-e4eb61be-fab2-11e7-8974-64d5c4256d8c.png)

Java 8
![image](https://user-images.githubusercontent.com/12251937/34984942-c985b118-fab2-11e7-987b-026bff8fedd2.png)

As can bee seen, 8 v 9 uses different classloader while launching jar. Java 8 one is extending URLClassloader, Java 9 one is **not**

Can be tested by following project

[vertx-test.zip](https://github.com/eclipse/vert.x/files/1634735/vertx-test.zip)

**Comment by vietj** [comment]
yes it's expected and we have no way go fix it, so it should be documented I think in the method.

**Comment by vietj** [comment]
can you take care of this @cescoffier ?

**Comment by cescoffier** [comment]
I will @vietj

**Comment by cescoffier** [comment]
Comment added in the master branch.

**Comment by nabil-mansouri** [comment]
Hi guys!
Do you plan to fix class loader isolation on Java 9+?
@cescoffier  could you reopen this issue? 
Because we could not imagine change our architecture because of that. It seems that spring boot had a similar problem (get urls from classloader to reload an application) and they have fixed it:
https://github.com/spring-projects/spring-boot/blob/c1f7aa801a6c66b38c8b644ce50f05322980a4d2/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/restart/DefaultRestartInitializer.java

It would be very nice if this bug could be fixed. 

Thanks

**Comment by vietj** [comment]
@nabil-mansouri we actually have less classloading in vertx core itself

Isolation groups should be deprecated and moved out from core in 4.0, in a separate module that would be compatible with Java 8 and perhaps might also include Java > 8 hacks / fixes.
