### ISSUE TITLE
Event Bus:  "Handlers.choose()" should deprioritize paused handlers

### ISSUE THREAD

**Issue by sfitts** [eclipse/vert.x#2489]
Version -- 3.5.1

Currently when a message is handled by the bus the "choose" code will simply pick the next handler in line.  If it turns out that handler is paused, the message will get dropped on the pending queue and possibly discarded, even if there are other handlers on the same address that are available to process the message.  It would be preferable if it gave preference to handlers that are not paused over those that are when making this choice.

**Comment by vietj** [comment]
Hi Sean,

I don't think that is something we could do efficiently because it could imply lot of contention between threads.

that being said I'm not saying we should not achieve it, but we should do it using different coordination. I will close this issue and add to the event bus roadmap the feature to use the actual handler capacity for routing the message.

**Comment by sfitts** [comment]
Sounds good -- I have a Q&D solution that works for the case of entirely local addresses, but in general I think it would be nice to see some improvements in the flow control/work distribution on the bus (a large/thorny topic to be sure, but what's there now is very constrained in the use cases it addresses).
