### ISSUE TITLE
eventBus.send blocks in for loop

### ISSUE THREAD

**Issue by MrGarry2016** [eclipse/vert.x#2496]
Just found that eventBus.send blocks when using for loop, it will finish all the send, then process the reply.

Send.java
for(int i = 0 ; i < 5 ; i++){
       System.out.println("sending");
        eventBus.send("addr", message, re -> {
            System.out.println("done");    
        });
}

Consumer.java
vertx.eventBus().consumer("addr", e -> {
            System.out.println("Receive message " + e.body());
        });

The above code produces this output:
sending
sending
sending
sending
sending
Receive message
Receive message
Receive message
Receive message
Receive message

Is there a way I can have interleave send/receive when usingh for loop?

Thanks

**Comment by vietj** [comment]
the behaviour your describe depends on the event loop you are executing, with two different event loops this will be done concurrently.

if you are using the same event loop, indeed that will happen because event loop is single threaded and there is no magic by which vertx could run the code concurrently.

normally your app should not depend on this, if you really need something concurrent, you can wrap each event bus send as a context task:

```
for(int i = 0 ; i < 5 ; i++){
vertx.runOnContext(v -> {
System.out.println("sending");
eventBus.send("addr", message, re -> {
System.out.println("done");
});
});
}
```
